### PR TITLE
Media Updates - July 2022

### LINKED ISSUE #22: Ferroseed cry is wrong, it’s playing the one for venipede instead

### PR DESCRIPTION
**Pull request by sora10pls**
Hello again! I've been looking back at the project these last few days, and have some updates to share with you.

Presented changes:
* `index.html` - Update `genSelectContainer` for slight grammar fixes, and label more games where appropriate.
* Media (images and sounds) - some new updates from me! A more in-depth list is below.

Images:
* Add official Ken Sugimori artwork for Ursaluna, Sneasler, Overqwil, and Incarnate Forme Enamorus
* Revise artwork for Unfezant, Frillish, Jellicent, and Basculegion to display both genders - this is already done with Pyroar, Meowstic, and Indeedee, so wanted to remain consistent wherever possible

Sounds:
* Better MP3 compression
* Fix an issue where Ferroseed still had Venipede's cry (resolves #22)
* Fix an issue where Gulpin's cry was erroneously Makuhita's

For posterity, I've double-checked all of the cry data, and can verify accuracy and no regressions with the site when running locally on my machine. My proposed changes for images and sounds can be [downloaded here](https://mega.nz/file/RZ1jUBKA#Odq_yjWzXgjDa4t7rlkq-_cCM_YqeKQuuY3J0OntI8M).

P.S. I plan on reaching out to you again when Scarlet and Violet are released, to hopefully have support for Generation 9 as soon as possible! I recently wrote a LINQPad script that uses PKHeX.Core to generate arrays of species name translations for use with the project (it can be found [here](https://pastebin.com/x8Y84UVi) on my Pastebin), so it will make future additions much more streamlined.

### CODE REVIEW

**Comment by Menardi** [comment]
Hi Matt, thanks for more great work on this! It'll be great to have a PR for gen 9 when it comes out, I look forward to it.

Regarding the images showing both male and female versions, I think it might actually be better to change the existing ones so they only show a single Pokémon instead of two. It wasn't an intentional choice that the existing ones show male and female together, but rather that's just how they came from Bulbapedia. I must have missed them when adding these images a while ago. Could you instead change Pyroar, Meowstic and Indeedee to be a single image? I suggest choosing whichever form you think is more unique and recognisable.

**Comment by sora10pls** [comment]
As per your request, I've gone ahead and [updated all of the varied gender artwork](https://mega.nz/file/0Vs3GQiY#vGElmx745AcbjL5j9fl8DD5XzTjmX9HL0w_WcV2ZnUs) to only display one of the two. I opted to choose the males in all instances, since that's generally what they do in-game, and in Indeedee's case, that's the cry provided to the project (male and female have unique cries).

**Comment by Menardi** [comment]
That's great, thanks! I'll get these updates added this weekend.

**Comment by Menardi** [comment]
I've replaced the images with the ones you've supplied, and replaced the incorrect sound files. I didn't replace the rest of the MP3s, as most users probably have the existing cries cached in their browsers now, so it's faster to keep the existing ones.

I also ran a quick checksum across the sounds files to confirm they're all different now, so there should be no more duplicates.

I'll merge this PR now, and the changes should be deployed along with the image and sound fixes within the next hour or so. Thanks again for your contribution!

**Pull request merged**
